### ISSUE TITLE
Broken links in the online manual

### ISSUE THREAD

**Issue by wilfwilson** [semigroups/Semigroups#743]
In the manual, as well as referencing other parts of the manual, we reference things in other manuals, e.g. we reference things from the GAP manual, Digraphs, Smallsemi, and GAPDoc.

There are some problems with referencing in [the online version](https://semigroups.github.io/Semigroups/doc/chap0.html):
* References to GAP's manual are completely broken, e.g: the reference to `Transformation` in https://semigroups.github.io/Semigroups/doc/chap1.html#X8389AD927B74BA4A appears as `???` (**this applies to the pre-compiled manual in the released version, too!**).
    * This is because @james-d-mitchell's local GAP reference manual wasn't compiled when he made the most recent release.
* References to the Digraphs manuals appear nicely, but the links don't resolve, such as the reference to `Digraph` in https://semigroups.github.io/Semigroups/doc/chap14.html#X7EA002E27B10CCE0
    * The link is pointing to <https://semigroups.github.io/pkg/digraphs/doc/chap3_mj.html#X834843057CE86655>, which obviously fails.
* References to GAPDoc's manual too: https://semigroups.github.io/Semigroups/doc/chap19.html#X7F51F3CD7E13D199
    * Which points to: <https://semigroups.github.io/pkg/GAPDoc-1.6.4/doc/chap6_mj.html#X7E14D32181FBC3C3>

This is a slightly tricky issue.

The online version of the manual is a copy of the releaser's local HTML manual that's built as part of the release process. The hyperlinks that are produced as part of this are defined locally for the releaser's system, and are very much version-specific to the particular versions of GAP/packages used.

This presents some problems:
1. The manuals referenced from the Semigroups package manual must be compiled on the releaser's local system, by the time that the release is made.
1. The local HTML hyperlinks will not work when uploaded to the internet; different manuals are hosted at different domain names, but since the links are local, you'll end up with links like `https://semigroups.github.io/pkg/digraphs/doc/...` (as above) which just won't work! (Unless you also upload the Digraphs manual to that location, which I don't recommend).
1. If the local versions of GAP/Digraphs/etc were different from the versions of GAP/Digraphs that produced the online versions of _their own manuals_, then there's still a good chance that some links will be broken (since manuals typically change between releases).

The first of these problems is quite easy to fix. Determining which manuals to compile, and compiling them, could be part of the release script.

The second problem requires a technical solution. It seems like it is solved already, for the case of referencing the GAP manual. See [this chapter of the `images` package's manual](https://gap-packages.github.io/images/doc/chap3.html#X876D239D80880D03) for an example of an online manual successfully referencing the GAP reference manual. Presumably, part of the release tools is doing some sort of search-and-replace on the compiled HTML, and thereby updating links to the GAP reference manual to the appropriate URL. This should be investigated, and extended so that it covers links to the other manuals that we reference.

The third problem is an organisational one. It is also the least important. To solve it properly, the online version of the manual should be compiled from a local setup with GAP and package versions that match the versions whose online manuals we want to link to. Typically, this will be the latest released version of GAP, and Digraphs/GAPDoc/Smallsemi.

(This issue also applies, to a lesser degree, to the Digraphs package).

**Comment by wilfwilson** [comment]
Here's the line in @fingolfin's `ReleaseTools` that updates the local hyperlinks to GAP's manual to be proper URLs: https://github.com/gap-system/ReleaseTools/blob/b5182b2562f0102e17e95d53ebe88e1b97cf490e/release-gap-package#L595

So we need to do something similar for the other packages whose manuals we cite. This should be the URL we use for the GAPDoc base <http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc/doc/>, obviously Digraphs should be <https://digraphs.github.io/Digraphs/doc/>, etc.

**Comment by james-d-mitchell** [comment]
Thanks @wilfwilson I'm going to try to resolve this by updating the release script to do these steps, thanks for the careful analysis!

**Comment by james-d-mitchell** [comment]
@wilfwilson I believe I've fixed all of these issues with the introduction of the `.release` script in PR #744

**Comment by james-d-mitchell** [comment]
@wilfwilson I think this is fixed in v3.4.2 the links in the manual seem to work ok now.

**Comment by wilfwilson** [comment]
Thanks @james-d-mitchell, this seems to work nicely! Shall I make a similar issue for the Digraphs package? I'll also submit a PR soon for your new `.release` script - in particular, after now looking at the GAP manual, I think we shouldn't be deleting the `doc/manual.lab` file, in case other manuals want to reference Semigroups:
```
  The  archive  of  a  GAP package should contain all files necessary for the
  package  to  work.  In particular there should be a compiled documentation,
  which  includes  the  manual.six,  manual.toc  and  manual.lab  file in the
  documentation  subdirectory  which  are  created by GAPDoc while TeXing the
  documentation.  (The first two files are needed by the GAP help system, and
  the  manual.lab  file  is  needed if the main manuals or another package is
  referring  to your package. Use the command GAPDocManualLab( packagename );
  to create this file for your help books if you use GAPDoc.)
```

**Comment by wilfwilson** [comment]
However, I do somewhat disagree with the `sed`ing of the hyperlinks in the released version of the package. I think that should only be done for the version of the manual that gets uploaded to the website (in particular it could be done after the release is wrapped). For the released version, I think the links should still be local, so that it's still useful on a system without an active internet connection. But since we always seem to have an internet connection these days, it's not a huge problem.

I also think it's possible that deleting the `makedoc.g` file from the released version might mess up some GAP-infrastructure-related scripts, but I don't think that should be our concern right now.

**Comment by james-d-mitchell** [comment]
Thanks @wilfwilson, that's a good point, I didn't really think about the archive version of the docs when doing this. I pretty sure we can amend the release scripts to account for this next time. 

Also about deleting `makedoc.g`, I agree that deleting it is not optimal, but at present I don't see an alternative. The reason for doing this is that the Semigroups package needs to be loadable for `makedoc.g` to run (because it is loaded by `GAPDocManualLab`). I am not sure if this step is really essential, I don't recall why this is included, nor could I find other examples in `gap-packages` (they all seem to use autodoc these days).

With the current version of the `release-gap-package` script in the release tools, the `.release` script is run, and then the doc is built by detecting either `makedoc.g` or `doc/make_doc`. We can, of course, build the Semigroups package in the `.release` script, and then let `release-gap-package` build the doc, but this would lead to the build files (`.o` files etc) being included in the archive. We could also just build the doc in the `.release` script, and then remove the build files (`make distclean`) and then let `release-gap-package` try to build the doc, but this would fail, because `Semigroups` is not loadable. So, it seemed like the least evil way to use `release-gap-package` without modifications was to just delete the `makedoc.g` file.  

If a `make distclean` were included in the `release-gap-package` script just before `./autogen.sh` is called and the running of `autogen.sh` was moved in `release-gap-package` to after the doc was built, then I think this would resolve things, so that we can keep `makedoc.g` and allow `release-gap-package` to build the doc. There might be other reasons that this isn't desirable though. 

Another solution would be to allow the building of the Semigroups docs without the package being loaded, but I'm not sure how to achieve this at present because of the call to `GAPDocManualLab`.

**Comment by wilfwilson** [comment]
Thanks for the explanation. I think for now our solution with deleting `makedoc.g` is fine.

If we want to improve things further, we can consider whether the most appropriate thing would be to make a PR to [ReleaseTools](https://github.com/gap-system/ReleaseTools). I might make a couple of issues. We could also consider whether we can make GAP's `GAPDocManualLab` not need to load the package.

**Comment by wilfwilson** [comment]
I've made issues on these topics at https://github.com/gap-system/ReleaseTools/issues/73 and https://github.com/gap-system/ReleaseTools/issues/74.

For now our solution is okay (and we'll presumably do something similar for Digraphs). But perhaps in future ReleaseTools will be updated to include our use case, letting us reduce our custom code.
