### ISSUE TITLE
do not link libstdc++ unconditionally

### ISSUE THREAD

**Issue by dimpase** [semigroups/Semigroups#928]
https://github.com/semigroups/Semigroups/blob/4056547e7130abab1700e6056429600196a192bd/Makefile.in#L7

By right, with clang toolchain, the correct library is libc++
The present config causes breakage on arm64 (M1) macOS as reported on GAP Forum (and we tracked this down to this place)
```
Date: Fri, 23 Jun 2023 11:50:40 +0200
From: lfsequeira <forum@gap-system.org>
To: forum@gap-system.org
Subject: [GAP Forum] Loading packages on Apple Silicon Macs
X-Mailer: Sympa 6.1.23

[-- Attachment #1 --]
[-- Type: text/plain, Encoding: 7bit, Size: 1.6K --]

Hello

I am using GAP 4.12.2 on both Intel and M1 MAX Macs - both running Ventura
13.4, with the latest version of XCode installed.

I can successfully compile GAP and the packages on both platforms.
On an Intel Mac, everything works.
On the M1 MAX, loading packages written in GAP is fine, but loading packages
with compiled C or C++ code (like, for example, Semigroups) does not work.
Running
  LoadPackage("Semigroups"); #or also with other compiled packages

I get this error message in GAP:


Error, LOAD_DYN: failed to load kernel module /Users/lsequeir/Applications/
gap-4.12.2/pkg/semigroups/bin/aarch64-apple\
-darwin22-default64-kv8/semigroups.so, dlopen(/Users/lsequeir/Applications/
gap-4.12.2/pkg/semigroups/bin/aarch6\
4-apple-darwin22-default64-kv8/semigroups.so, 0x0005): symbol not found in
flat namespace '__ZN13libsemigroups1\
9CongruenceInterface19word_to_class_indexERKSt6vectorImSaImEE' in
  LOAD_DYN( filename ) at /Users/lsequeir/Applications/gap-4.12.2/lib/
files.gd:592 called from
<function "LoadDynamicModule">( <arguments> )
 called from read-eval loop at /Users/lsequeir/Applications/gap-4.12.2/pkg/
semigroups/init.g:22
Error, was not in any namespace at /Users/lsequeir/Applications/gap-4.12.2/
lib/variable.g:269 called from
LEAVE_NAMESPACE(  ); at /Users/lsequeir/Applications/gap-4.12.2/lib/
package.gi:1325 called from
ReadPackage( pkgname, "init.g" ); at /Users/lsequeir/Applications/gap-4.12.2/
...
```
the correct way to fix this is to test in `./configure` which C++ library should be used, and fill the template in `Makefile.in` with the correct value.

**Comment by james-d-mitchell** [comment]
Thanks for the report @dimpase, for some reason I don't get the forum emails any longer. 

@fingolfin is this something that you might be able to look at? Thanks!

**Comment by james-d-mitchell** [comment]
@dimpase when you write:

> the correct way to fix this is to test in ./configure which C++ library should be used, 

Am I detecting the os (which I can see how to do), or detecting the compiler (seems to be hard)?

**Comment by dimpase** [comment]
one has to detect the toolchain here. It's perfectly feasible to have
clang++ toolchain, with libc++, on Linux.

Let me dig up relevant autoconf for this.

**Comment by dimpase** [comment]
Sagemath is using  [`AX_COMPILER_VENDOR`](https://www.gnu.org/software/autoconf-archive/ax_compiler_vendor.html)
So you can do it too:
```
    AC_LANG_PUSH([C++])
    AX_COMPILER_VENDOR()
    AS_IF([test "x$ax_cv_c_compiler_vendor" = xclang], 
               [< put  -lc++ into the right place  >], dnl it's clang++ ! 
               [<< put  -lstdc++ into the right place  >])
```
```

**Comment by james-d-mitchell** [comment]
Thanks @dimpase !

**Comment by dimpase** [comment]
I suppose you know what to do now: copy this macro into your sources, replace 
`KEXT_LDFLAGS = -lstdc++  # add C++ library` with `KEXT_LDFLAGS = @FOOBAR_CPPLIB@  # add C++ library` in `Makefile.in`, and set `FOOBAR_CPPLIB` accordingly in `AS_IF` cases above.

**Comment by james-d-mitchell** [comment]
Yup thanks @dimpase I know what to do now!

**Comment by fingolfin** [comment]
On the long run, a potentially simpler approach might be to use the C++ compiler to link the kext instead of the C compiler. Then it will automatically pick the right library.

But I did not try it, so I am not 100% sure it works, someone would have to try it.

The downside is that right now this would required patching `gac`, so it's not an immediate solution. But if we establish that it helps, I'd be happy to work on a patch for `gac` so that in the next GAP release, there is a way to tell it to use C++ to link (e.g. by providing a flag to choose that, or just providing a general way to override the linker, dunno)

**Comment by fingolfin** [comment]
@james-d-mitchell regarding the GAP forum: when the GAP mailing lists were still hosted in St Andrews, they had problems that caused people *from St Andrews* to become unsubscribed because the St Andrews mail servers thought these were forged / spam... So maybe you've been unsubscribed since before we moved the lists last year?

Anyway, I don't see any email address matching `jdm` or `mitchell` on the GAP forum subscriber list. You may wish to re-subscribe to it and possible other lists (e.g. the `gap` list).

**Comment by james-d-mitchell** [comment]
@fingolfin thanks @fingolfin I'll resubscribe, thanks for the explanation!

**Comment by dimpase** [comment]
> On the long run, a potentially simpler approach might be to use the C++ compiler to link the kext instead of the C compiler. Then it will automatically pick the right library.
> 
> But I did not try it, so I am not 100% sure it works, someone would have to try it.

on #937 I report on an unsuccessful attempt to build semigroups.so on OpenBSD, which resulted in unusable (ldd errors out, GAP's LoadPackage as well). And the file size is 218Mb - something is seriously off.
